# Introduction 
- Numpy is a python library for creating and manipulating matrices, the main data structure used by ML algorithms. Matrices are mathematical objects used to store values in rows and columns

- python calls matrices <i>lists</i>, NumPy calls them <i>arrays</i> and TensorFlow calls them <i>tensors</i>. Python represents matrices with the list data type.

In [2]:
# Import numpy module
import numpy as np

# Populate arrays with specific numbers

Call "np.array" to create a NumPy array with your own hand-picked values. For example, the following call to "np.array" creates and 8-element array:

In [3]:
one_dimensional_array = np.array([1.2,2.4,3.5,4.7,6.1, 7.2, 8.3, 9.5])
print(one_dimensional_array)

[1.2 2.4 3.5 4.7 6.1 7.2 8.3 9.5]


You can also use np.array to create a two-dimensional array. To create a two-dimensional arrray specify an extra layer of square brackets. For example the following call creates a 3X2 array:

In [4]:
two_dimensional_array = np.array([[6,5],[11,7],[4,8]])
print(two_dimensional_array)

[[ 6  5]
 [11  7]
 [ 4  8]]


To populate an array with all zeros, call [np.zeros]. To popluate an array with all ones, call [np.ones].

# Popluate arrays with sequence of numbers:

- You can populate an array with a sequence of numbers: 

In [17]:
sequence_of_integers = np.arange(5,12)
all_zeros = np.zeros([2, 10])
all_ones = np.ones([2,10])
print(sequence_of_integers)
print(all_zeros)
print(all_ones)

[ 5  6  7  8  9 10 11]
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


[np.arange] generates a sequence that includes the lower bound(5) but not the upper bound(12).

# Populate arrays with random numbers

NumPy provides various functions to populate arrays with random number across certain ranges. For example, [np.random.randint] generate random intergers between a low and high value. The following call populates a 6-element array with random integers between 50 and 100.

In [10]:
random_integers_between_50_and_100 = np.random.randint(low=50, high=101, size=(6))
print(random_integers_between_50_and_100)

[50 82 97 51 98 98]


Note that the highest generated interger <b>np.random.randing</b> in one less than <b>high</b>argument.

To create a random floating-point values between 0.0 and 1.0, call <b>np.random.uniform</b>  and <b>np.random.random</b>

In [27]:
# random_floating_point_numbers = np.random.uniform(low=5, high=10, size=(6))
# print(random_floating_point_numbers)
random_floats_between_0_1 = np.random.random((6,))
print(random_floats_between_0_1)

[8.70942956 7.30005694 5.99929329 7.3705644  9.49832931 6.31618872]
[0.54409191 0.18741709 0.37381037 0.75184172 0.37269326 0.68418298]


# Mathematical operation on NumPy Operands

If you want to add or subtract two arrays, linear algebra requires that two operands have the same dimensions. Furthermore, if you want to multiple two arrays, linear algebra imposes strict rules on the dimensional compatibility of operands. Fortunately, Numpy uses a trick called <a href="https://developers.google.com/machine-learning/glossary/#broadcasting">brodcasting</a> to virtually expand the smaller operand to dimensions compatible for linear algebra. For example, the following operations uses broadcasting to add 2.0 to the value of every item in the array created in the previous code cell. 

In [29]:
random_floats_between_2_and_3 = random_floats_between_0_1 + 2.0
print(random_floats_between_2_and_3)

[2.54409191 2.18741709 2.37381037 2.75184172 2.37269326 2.68418298]


The following operation also relies on broadcasting to multiple each cell in an array by 3: 

In [30]:
random_integers_between_150_and_300 = random_integers_between_50_and_100 * 3
print(random_integers_between_150_and_300)

[150 246 291 153 294 294]


# Task 1: Create a Linear Dataset

Goal is to create a simple dataset consisting of a single feature and a label as follows:

1. Assign a sequence of integers from 6 to 20(inclusive) to a NumPy array named `Feature`.
2. Assign 15 values to a NumPy array names `Label` such that

```
label = (3)(feature) + 4
```
For example, the first value for `label` should be:

```
label = (3)(6) + 4 = 22
```


In [36]:
feature = np.arange(6,21)
print(feature)
label = (feature * 3) + 4
print(label)


[ 6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[22 25 28 31 34 37 40 43 46 49 52 55 58 61 64]
22


# Task 2: Add some noise to the Dataet

To make dataset a little more realistic, insert a little random noise into each element of the label array you already created. To bemore precise, modify each value assignet  to `label` by adding a different random floating-point value between -2 and +2. 

In [38]:
noise  = (np.random.random([15]) * 4) - 2
print(noise)
label = label + noise
print(label)

[-0.29240036  1.67280991 -0.36229437  0.11662891 -0.2045169  -0.70147784
  1.18674908  0.46910767 -1.05151931  1.46572746 -1.02070357 -1.51573599
 -1.12235933 -0.87430868 -1.27603534]
[21.70759964 26.67280991 27.63770563 31.11662891 33.7954831  36.29852216
 41.18674908 43.46910767 44.94848069 50.46572746 50.97929643 53.48426401
 56.87764067 60.12569132 62.72396466]
