In [1]:
import numpy as np
print(np.__version__)

2.2.1


In [2]:
# How to create a 1D array?
# Qs. Create a 1D array of number from 0 to 9
# output : #> array([0,1,2,3,4,5,6,7,8,9])\

x = np.arange(10)
print(x)

[0 1 2 3 4 5 6 7 8 9]


In [3]:
# Question: Create a 3*3 numpy array of all True'set

# solution 
one = np.full((3,3), True, dtype=bool)
print(one)

# or
two = np.full((9), True, dtype=bool).reshape(3,3)
# print(two)
# or 
three = np.ones((3,3), dtype=bool)
# print(three)
# or 

four = np.ones((9), dtype=bool).reshape(3,3)
# print(four)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


## How to Extract items that statisfy a given condition from 1D array?

In [4]:
# Qs. Extract all odd numbers, and even numbers from array 
# input: arr = np.array([0,1,2,3,4,5,6,7,8,9])
# output: array([1,3,4,5,7,9])

arr = np.arange(10)

print("Odd numbers from the array: ",arr[arr%2 == 1])
print("Even numbers from the array", arr[arr%2 == 0])

Odd numbers from the array:  [1 3 5 7 9]
Even numbers from the array [0 2 4 6 8]


## How to replace items that statisfy a condition with another value in numpy array?

In [5]:
# Qs. Replace all odd numbers in arr with -1
# input arr = np.array([0,1,2,3,4,5,6,7,9])
# output: arr([0,-1,2,-1,4,-1,6,-1,8,-1])

# solution

arr = np.arange(10)

arr[arr%2 == 1] = -1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

## How to replace items that satify a condition without affecting the original array

In [6]:
# Qs: Replace all odd numbers in arr with -1 without changing arr
# input: arr = np.array([0,1,2,3,4,5,6,7,8,9])
# output : 0ut 
# Mofied Array:  [ 0 -1  2 -1  4 -1  6 -1  8 -1]
# Orignal Array [0 1 2 3 4 5 6 7 8 9]

arr = np.arange(10)
out = arr.copy()

out[out%2 == 1] = -1

print('Mofied Array: ', out)

print("Orignal Array", arr)

Mofied Array:  [ 0 -1  2 -1  4 -1  6 -1  8 -1]
Orignal Array [0 1 2 3 4 5 6 7 8 9]


## HOW TO RESHAPE ARRAY

In [7]:
# Question: Convert a 1D array to a 2d array with 2 rows
# input: np.arange(10)
# output array([0,1,2,3,4],
#              [5,6,7,8,9])

# solution
arr = np.arange(10)
print(arr.reshape(2,5))

# another solution
arr = np.arange(10)
print(arr.reshape(2,-1)) # setting -1 automatically decides the number of cols

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1 2 3 4]
 [5 6 7 8 9]]


## HOw to stack two arrays vertically? 

In [8]:
## Question: Stack array a and b vertically
# input: a = np.arange(10).reshae(2,-1)
#        b = np.repeat(1,10).reshape(2,-1)

# ouput: array([[0,1,2,3,4],
#               [5,6,7,8,9],
#               [1,1,1,1,1],
#               [1,1,1,1,1]]) 

a = np.arange(10).reshape(2,-1)
b = np.repeat(1,10).reshape(2,-1)

np.vstack([a,b])

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

## How to stack two arrays horizontally

In [9]:
# Question: Stack the arrays aa nd b horizontally

#Input: a = np.arange(10).reshape(2,-1)
#       b = np.repeat(1,10).reshape(2,-1)
# Output: array([0,1,2,3,4,1,1,1,1,1],
#               [5,6,7,8,9,1,1,1,1,1])

# solution 
a = np.arange(10).reshape(2,-1)
b = np.repeat(1,10).reshape(2,-1)

np.hstack([a,b])

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

## How to geenrate custom Sequence in numpy without hardcoding

In [10]:
# Question: Create a following patter without hardcoding. Use only numpy fucntions and the below input array a
# Input: a = np.array([1,2,3])
# Output: array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

# solution 
a = np.array([1,2,3])
np.r_[np.repeat(a,3), np.tile(a,3)] # r_ is a convenience function for concatenating arrays along the first axis

# np.repeat(a,3): [1, 1, 1, 2, 2, 2, 3, 3, 3]
# np.title(a,3): [1, 2, 3, 1, 2, 3, 1, 2, 3]
# concatenated result =  [1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3]


array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

## 11. How to get the common items between two python numpy arrays?

In [11]:
# Question: Get the common items between a and b

# Input: a = np.array([1,2,3,2,3,4,3,4,5,6])
#        b = np.array([7,2,10,2,7,4,9,4,9,8])

# Output: array([2, 4])

a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

np.intersect1d(a,b)


array([2, 4])

## 12. How to remove from one array those items that exist in another? 

In [12]:
# Question: From array a remove all items present in array b

# Input: a = np.array([1,2,3,4,5])
#        b = np.array([5,6,7,8,9])

# Output: array([1,2,3,4])


# Solution

a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
np.setdiff1d(b,a)

array([6, 7, 8, 9])

## 13. How to get the positions where elements of two arrays match? 

In [13]:
# Question: get the positions where elements of a and b match
# Input: a = np.array([1,2,3,2,3,4,3,4,5,6])
#        b = np.array([7,2,10,2,7,4,9,4,9,8])

# Output: (array([1, 3, 5, 7]),)


# Solution
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.where(a == b)

(array([1, 3, 5, 7]),)

## 14. How to extract all numbers between a given range from a numpy array? 

In [14]:
# Question: Get all items between 5 and 10 from a.

# Input: a = np.array([2, 6, 1, 9, 10, 3, 27])
# Output: (array([6, 9, 10]),)


# Solution

a = np.array([2,6,1,9,10,3,27])
a[(a >= 5) & (a <= 10)]

array([ 6,  9, 10])

## 15.How to make a python function that handles scalers to work on numpy arrays?

In [15]:
# Question: Convert the function maxx that works on two scalers, to work on two arrays. 

# Input: 
def maxx(x,y):
    """Get the maximum of two items"""
    if x >= y: 
        return x
    else: 
        return y
# maxx(1,5)
# > 5 
# Output:
# a = np.array([5, 7, 9, 8, 6, 4, 5])
# b = np.array([6, 3, 4, 8, 9, 7, 1])
# pair_max(a, b)
# array([ 6.,  7.,  9.,  8.,  9.,  7.,  5.])

# Solution
def pair_max(x,y):
    # Here  i am using map to make tuple from a and b, other solution is using zip(a,b)
    maximum = [maxx(a,b) for a,b in map(lambda a,b:(a,b),x,y)]
    # using zip
    # maximum = [max(a,b) for a,b in zip(x,y)]
    return np.array(maximum)

a = np.array([5,7,9,8,6,4,5])
b = np.array([6,3,4,8,9,7,1])

pair_max(a,b)

array([6, 7, 9, 8, 9, 7, 5])

## 16. How to swap to columns in a 2d numpy array?

In [16]:
# Question: Swap columns 1 and 2 in the array arr.

# Input:
arr = np.arange(9).reshape(3,3)

print('Orignal Array')
print(arr)

print("\nModified Array")
arr[:, [1,0,2]]

Orignal Array
[[0 1 2]
 [3 4 5]
 [6 7 8]]

Modified Array


array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

## 17. How to swap two rows in a 2d numpy array?

In [17]:
# Question: Swap rows 1 and 2 in the array arr:

# Input: 

arr = np.arange(9).reshape(3,3)
print('Original array\n',arr)


# solution 

print("\nModified Array")
arr[[2,1,0], :]

Original array
 [[0 1 2]
 [3 4 5]
 [6 7 8]]

Modified Array


array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

## 18. How to reverse the rows of 2D array?

In [18]:
# Question: Reverse the rows of a 2D array arr.

# Input:

arr = np.arange(9).reshape(3,3)
print('Original array\n',arr)

print("\nModified array")
arr[::-1, :]


Original array
 [[0 1 2]
 [3 4 5]
 [6 7 8]]

Modified array


array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

## 19. HOw to reverse the column of a 2D array?

In [19]:
# Question: Reverse the columns of a 2D array arr.

# Input: arr = np.arange(9).reshape(3,3)

# Solution

arr = np.arange(9).reshape(3,3)
print('Orignal Array\n',arr)


print("\nModified array")
arr[:, ::-1]

Orignal Array
 [[0 1 2]
 [3 4 5]
 [6 7 8]]

Modified array


array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

## 20. How to create a 2D array containing random floats between 5 and 10

In [20]:
# Question: Create a 2D array of shape 5x3 to contain random decimal numbers between 5 and 10.

# Solution:
rand_arr = np.random.uniform(5,10, size=(5,3))
rand_arr

array([[9.11929162, 6.90959253, 7.53527389],
       [6.95914646, 8.65293237, 6.19004163],
       [9.93066631, 8.77387848, 5.44296682],
       [6.40760626, 7.83865263, 9.42172792],
       [6.43256973, 9.92138133, 8.66456264]])

## 21. How to print only 3 decimal places in python numpy array?

In [21]:
# Question: Print or show only 3 decimal places of the numpy array rand_arr
rand_arr = np.random.random((5,3))
np.set_printoptions(precision=3)
rand_arr

array([[0.742, 0.168, 0.5  ],
       [0.229, 0.998, 0.357],
       [0.799, 0.372, 0.955],
       [0.949, 0.732, 0.146],
       [0.007, 0.8  , 0.984]])

## 22. How to pretty print a numpy array by suppressing the scientific notation (like 1e10)?

In [22]:
# Pretty print rand_arr by suppressing the scientific notation (like 1e10)

# Input: 
# Create the random array
np.random.seed(100)
rand_arr = np.random.random([3,3])/1e3
np.set_printoptions(suppress=False)
print(rand_arr)

# Output:
#> array([[ 0.000543,  0.000278,  0.000425],
#>        [ 0.000845,  0.000005,  0.000122],
#>        [ 0.000671,  0.000826,  0.000137]])

np.set_printoptions(suppress=True)
print(rand_arr)
#> array([[ 0.000543,  0.000278,  0.000425],
#>        [ 0.000845,  0.000005,  0.000122],
#>        [ 0.000671,  0.000826,  0.000137]])

[[5.434e-04 2.784e-04 4.245e-04]
 [8.448e-04 4.719e-06 1.216e-04]
 [6.707e-04 8.259e-04 1.367e-04]]
[[0.001 0.    0.   ]
 [0.001 0.    0.   ]
 [0.001 0.001 0.   ]]


## 23. How to limit the number of items printed in output of numpy array?

In [23]:
# Question: Limit the number of items printed in python numpy array a to a maximum of 6 elements.
a = np.arange(15)
np.set_printoptions(threshold=6)
a

array([ 0,  1,  2, ..., 12, 13, 14], shape=(15,))

## 24. How to print the full numpy array without truncating

In [24]:
# Question: Print the full numpy array a without truncating.

# Input: np.set_printoptions(threshold=6)
# a = np.arange(15)
# a

# Output: a
#> array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

# Solution

a = np.arange(15)

np.set_printoptions(threshold=15)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

## 25. How import a dataset with numbers and texts keeping the text intact in python numpy?

In [25]:
# How to import the iris dataset keeping the text intact

# solution: 
iris_data = np.genfromtxt('./iris/Iris.csv', delimiter=',', skip_header=1, usecols=[0,1,2,3,4,5], dtype=object)
iris_data

array([[b'1', b'5.1', b'3.5', b'1.4', b'0.2', b'Iris-setosa'],
       [b'2', b'4.9', b'3.0', b'1.4', b'0.2', b'Iris-setosa'],
       [b'3', b'4.7', b'3.2', b'1.3', b'0.2', b'Iris-setosa'],
       ...,
       [b'148', b'6.5', b'3.0', b'5.2', b'2.0', b'Iris-virginica'],
       [b'149', b'6.2', b'3.4', b'5.4', b'2.3', b'Iris-virginica'],
       [b'150', b'5.9', b'3.0', b'5.1', b'1.8', b'Iris-virginica']],
      shape=(150, 6), dtype=object)

## 26. How to extract a particular column from 1D array of tuples?

In [26]:
# Question: Extract the text column species from the 1D iris imported in previous question.

data = np.genfromtxt('./iris/Iris.csv', delimiter=',', skip_header=1, usecols=[-1], dtype=object)
data

array([b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', ...,
       b'Iris-virginica', b'Iris-virginica', b'Iris-virginica'],
      shape=(150,), dtype=object)

## 27. How to convert a 1d array of tuples to a 2d numpy array?

In [27]:
# Question: Convert the 1D iris to 2D array iris_2d by omitting the species text field.
iris_data = np.genfromtxt('./iris/Iris.csv', delimiter=',', skip_header=1, dtype='float', usecols=[0,1,2,3])
iris_data

array([[  1. ,   5.1,   3.5,   1.4],
       [  2. ,   4.9,   3. ,   1.4],
       [  3. ,   4.7,   3.2,   1.3],
       ...,
       [148. ,   6.5,   3. ,   5.2],
       [149. ,   6.2,   3.4,   5.4],
       [150. ,   5.9,   3. ,   5.1]], shape=(150, 4))

## 28. How to compute the mean, median, standard deviation of a numpy array?

In [28]:
# Question: Find the mean, median, standard deviation of iris's sepallength (1st column)
iris_data = np.genfromtxt('./iris/Iris.csv', delimiter=',', skip_header=1, usecols=[1])
print('Mean', np.mean(iris_data))
print('Median',np.median(iris_data))
print('Standard Deviation',np.std(iris_data))

Mean 5.843333333333334
Median 5.8
Standard Deviation 0.8253012917851409


## 29. How to normalize an array so the values range exactly between 0 and 1?

In [29]:
# Question: Create a normalized form of iris's sepallength whose values range exactly between 0 and 1 so that the minimum has value 0 and maximum has value 1.

# Solution

iris_data = np.genfromtxt('./iris/Iris.csv', delimiter=',', dtype='float', usecols=[1], skip_header=1)
(iris_data - np.min(iris_data))/(np.max(iris_data) - np.min(iris_data))

array([0.222, 0.167, 0.111, ..., 0.611, 0.528, 0.444], shape=(150,))

## 30. How to compute the softmax score?

In [30]:
# Question: Compute the softmax score of sepallength.

iris_data = np.genfromtxt('./iris/Iris.csv', delimiter=',', dtype='float', usecols=[1], skip_header=1)
softmax = np.exp(iris_data)/sum(np.exp(iris_data))
softmax.sum() # it must sum 1
softmax


array([0.002, 0.002, 0.001, ..., 0.009, 0.007, 0.005], shape=(150,))

## 31. How to find the percentile scores of a numpy array?

In [31]:
# Question. Find the 5th and 95th percentile of iris's sepallength
iris_data = np.genfromtxt('./iris/Iris.csv', delimiter=',', dtype='float', usecols=[1], skip_header=1)
np.percentile(iris_data, q=[5,95])

array([4.6  , 7.255])

## 32. How to insert values at random positions in an array?

In [32]:
# Question: Insert np.nan values at 20 random positions in iris_2d dataset

iris_data = np.genfromtxt('./iris/Iris.csv', delimiter=',', dtype='float', usecols=[1], skip_header=1)
for i in np.random.randint(0,len(iris_data), 20):
    iris_data[i] = np.nan
iris_data

array([5.1, 4.9, 4.7, ..., 6.5, 6.2, 5.9], shape=(150,))

## 33. How to find the position of missing values in numpy array?

In [33]:
# Question: Find the number and position of missing values in iris_2d's sepallength (1st column)
iris_data = np.genfromtxt('./iris/Iris.csv', delimiter=',', dtype='float', usecols=[1,2,3,4], skip_header=1)
iris_data[np.random.randint(len(iris_data),size=20),np.random.randint(4,size=20)] = np.nan

# Find total missing value in complete data
print("Numer of missing values in Iris Data: \n", np.isnan(iris_data[:,:]).sum())

# Find total missing value in complete data
print("Number of missing values in any one feature of IriIris data: \n", np.isnan(iris_data[:,0]).sum())
print("Position of missing vlaues: \n", np.where(np.isnan(iris_data[:,0])))

Numer of missing values in Iris Data: 
 20
Number of missing values in any one feature of IriIris data: 
 5
Position of missing vlaues: 
 (array([ 38,  80, 106, 113, 121]),)


## 34. How to filter a numpy array based on two or more conditions?

In [34]:

iris_data = np.genfromtxt('./iris/Iris.csv', delimiter=',', dtype='float', usecols=[1,2,3,4], skip_header=1)

iris_data[(iris_data[:,2] > 1.5) & (iris_data[:, 0]< 5.0)]

array([[4.8, 3.4, 1.6, 0.2],
       [4.8, 3.4, 1.9, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [4.9, 2.4, 3.3, 1. ],
       [4.9, 2.5, 4.5, 1.7]], shape=(6, 4))

## 35. How to drop rows that contain a missing value from a numpy array?

In [35]:
# Question: Select the rows of iris_2d that does not have any nan value.
diabetes_data = np.genfromtxt('./diabetes/diabetes.csv', delimiter=',', dtype='float', usecols=[0,1,2,3,4,5,6,7], skip_header=1)
diabetes_data[np.random.randint(150, size=20), np.random.randint(4,size=20)] = np.nan
diabetes_data[np.sum(np.isnan(diabetes_data), axis=1) == 0][:5]

array([[  1.   ,  85.   ,  66.   , ...,  26.6  ,   0.351,  31.   ],
       [  8.   , 183.   ,  64.   , ...,  23.3  ,   0.672,  32.   ],
       [  1.   ,  89.   ,  66.   , ...,  28.1  ,   0.167,  21.   ],
       [  0.   , 137.   ,  40.   , ...,  43.1  ,   2.288,  33.   ],
       [  3.   ,  78.   ,  50.   , ...,  31.   ,   0.248,  26.   ]],
      shape=(5, 8))

## 36. How to find the correlation between two columns of a numpy array?

In [36]:
# question: Find the correlation between SepalLength(1st column) and PetalLength(3rd column) in iris_2d
# insted or using iris data I am going to used pima diabetes data and going to find corelation between BP(1st column) and BMI (5th column).
diabetes_data = np.genfromtxt('./diabetes/diabetes.csv', delimiter=',', dtype='float', usecols=[0,1,2,3,4,5,6,7], skip_header=1)

print(np.corrcoef(diabetes_data[:, 1], diabetes_data[:, 5]))

print('\n')
# You can get te correlation by getting value at index [0,1] or [1,0]

print(np.corrcoef(diabetes_data[:,1], diabetes_data[:,5])[0,1])


[[1.    0.221]
 [0.221 1.   ]]


0.2210710694589828


## 37. How to find if a given array has any null values?

In [37]:
# question: Find out if iris_2d has any missing values.
diabetes_data = np.genfromtxt('./diabetes/diabetes.csv', delimiter=',', dtype='float', usecols=[0,1,2,3,4,5,6,7], skip_header=1)
np.isnan(diabetes_data).any()


np.False_

## 38. How to replace all missing values with 0 in a numpy array?

In [38]:
# Question: Replace all ccurrences of nan with 0 in numpy array
wine_quality = np.genfromtxt('./wine/winequality-red.csv',
                             delimiter=',', dtype='float', usecols=[0,1,2,3,4,5,6,7,8,9,10], skip_header=1)
wine_quality[np.random.randint(len(wine_quality), size=20),np.random.randint(11,size=20)] = np.nan

print("Does dataset have any Nan value:", np.isnan(wine_quality).any())

wine_quality[np.isnan(wine_quality)] = 0

print("Does dataset have any Nan value:",np.isnan(wine_quality).any())

Does dataset have any Nan value: True
Does dataset have any Nan value: False


## 39. How find the count of unique values in a numpy array?

In [ ]:
# Question: Find the unique values and the count of unique values in mashroom data's habitat (22 column) column
mushroom = np.genfromtxt('./mushroom/mushrooms.csv',
                             delimiter=',', dtype=object, usecols=[0], skip_header=1)
np.unique(mushroom, return_counts=True)

(array([b'e', b'p'], dtype=object), array([4208, 3916]))

## 40. How to convert a numeric to a categorial (text) array?

In [40]:
# Question: Bin the petal length (3rd) column of iris_2d to form a text array, such that if petal length is:

# Less than 3 --> 'small'
# 3-5 --> 'medium'
# >=5 --> 'large'

# Solution
iris_data= np.genfromtxt('./iris/Iris.csv', delimiter=',', dtype=object, usecols=[3], skip_header=1)

bins = np.array([0,3,5,7])
inds = np.digitize(iris_data.astype('float'),bins)

labels = {1:'small', 2:'medium', 3:'large'}
iris_cat_data = [labels[x] for x in inds]
iris_cat_data[:10]


['small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small']

## 41. How to create a new column from exising columns of a numpy array?

In [41]:
# Question: Create a new column for volume in iris_2d, where volume is (pi x petallength x sepal_length^2)/3
iris_data = np.genfromtxt('./iris/Iris.csv', delimiter=',', 
                          dtype=object, usecols=[1,2,3,4], skip_header=1)

sepallength = iris_data[:, 0].astype('float')
petalllength = iris_data[:, 2].astype('float')

new_column = (np.pi * petalllength * (sepallength**2))/3

new_column = new_column[:,np.newaxis]

# Add the new column
out = np.hstack([iris_data, new_column])

# view
out[:4]

array([[b'5.1', b'3.5', b'1.4', b'0.2', 38.13265162927291],
       [b'4.9', b'3.0', b'1.4', b'0.2', 35.200498485922445],
       [b'4.7', b'3.2', b'1.3', b'0.2', 30.0723720777127],
       [b'4.6', b'3.1', b'1.5', b'0.2', 33.238050274980004]],
      shape=(4, 5), dtype=object)

## 42. How to do probabilistic sampling in numpy?

In [42]:
# Question: Randomly sample iris's species such that setose is twice the number of versicolor and virginica

iris_data = np.genfromtxt('./iris/Iris.csv', delimiter=',', 
                          dtype=object, usecols=[1,2,3,4], skip_header=1)

np.random.seed(100)
a = np.array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'])
species_out = np.random.choice(a, 150, [0.5,0.25,0.25])
print(np.unique(species_out,return_counts=True))

(array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype='<U15'), array([49, 46, 55]))


## 43. How to get the second largest value of an array when grouped by another way?

In [43]:
# Question: What is the value of second longest petallength of species setosa
# For this question I am going to find second highest bloodpressure (2nd column) where outcome is 1
diabetes_data = np.genfromtxt('./diabetes/diabetes.csv', delimiter=',', 
                          dtype=object, usecols=[0,1,2,3,4,5,6,7,8], skip_header=1)


bloodpressure = diabetes_data[diabetes_data[:,8] == b'1', [2]].astype('float')

np.unique(np.sort(bloodpressure))[-2]

np.float64(110.0)

## 44. How to sort a 2S array by a column 

In [44]:
# Question: Sort the iris dataset based on sepallength column.
# In this problem, I am going to sort the diabetes dataset based on Glucose (1th column)

diabetes_data = np.genfromtxt('./diabetes/diabetes.csv', delimiter=',', 
                          dtype=object, usecols=[0,1,2,3,4,5,6,7,8], skip_header=1)

diabetes_data[diabetes_data[:,1].argsort()]

array([[b'1', b'0', b'74', ..., b'0.299', b'21', b'0'],
       [b'5', b'0', b'80', ..., b'0.346', b'37', b'1'],
       [b'1', b'0', b'68', ..., b'0.389', b'22', b'0'],
       ...,
       [b'4', b'99', b'72', ..., b'0.294', b'28', b'0'],
       [b'4', b'99', b'76', ..., b'0.223', b'21', b'0'],
       [b'2', b'99', b'60', ..., b'0.453', b'21', b'0']],
      shape=(768, 9), dtype=object)

# 45. HOw to find the most fequent value of numpy array?

In [45]:
# Question: Find the most frequent value of petal length (3rd column) in iris dataset.

iris_data = np.genfromtxt('./iris/Iris.csv', delimiter=',', 
                          dtype=object, usecols=[1,2,3,4,5], skip_header=1)

v,c = np.unique(iris_data[:, 2], return_counts=True)

v[np.argmax(c)]

b'1.5'

## 46. How to find the position of the first occurrence of a value greater than a given value?

In [46]:
# Question: Find the position of the first occurrence of a value greater than 1.0 in 
# petalwidth 4th column of iris dataset.
iris_data = np.genfromtxt('./iris/Iris.csv', delimiter=',', 
                          dtype=object, usecols=[4], skip_header=1)

np.argwhere(iris_data[:].astype(float)> 1.0)[0]

array([50])

## 47. How to replace all values greater than a value to a given cutoff?

In [47]:
# Question: From the array a, replace all values greater than 30 to 30 and less than 10 to 10.

np.set_printoptions(precision=2)
np.random.seed(100)
a = np.random.uniform(1,50,20)

a[a<10] = 10
a[a>30] = 30
np.set_printoptions(threshold=20)
a

array([27.63, 14.64, 21.8 , 30.  , 10.  , 10.  , 30.  , 30.  , 10.  ,
       29.18, 30.  , 11.25, 10.08, 10.  , 11.77, 30.  , 30.  , 10.  ,
       30.  , 14.43])

## 48. How to get the positions of top n values from a numpy array?

In [48]:
# Question: Get the positions of top 5 maximum values in a given array a.
np.random.seed(100)
a = np.random.uniform(1,50,20)
print(a)
sort = a.argsort()
print('Positions',sort[-5:][::-1])

print('Values',a[sort][-5:][::-1])


[27.63 14.64 21.8  42.39  1.23  6.96 33.87 41.47  7.7  29.18 44.67 11.25
 10.08  6.31 11.77 48.95 40.77  9.43 41.   14.43]
Positions [15 10  3  7 18]
Values [48.95 44.67 42.39 41.47 41.  ]


## 49. How to compute the row wise counts of all possible values in an array?

In [49]:
# Question: Compute the counts of unique values row-wise.

def count_of_all_values_rowwise(arr2d):
    # Unique values and its counts row wise
    num_counts_array = [np.unique(row, return_counts=True) for row in arr2d]

    # counts of all values row wise 
    return([[int(b[a==i]) if i in a else 0 for i in np.unique(arr2d)] for a , b in num_counts_array])

np.random.seed(100)
np.set_printoptions(threshold=10)
arr = np.random.randint(1,11,size = (6,10))
print(arr)
print(np.arange(1,11))
count_of_all_values_rowwise(arr)


[[ 9  9  4 ...  3  6  3]
 [ 3  3  2 ... 10  7  3]
 [ 5  2  6 ...  8  2  2]
 [ 8  8  1 ...  3  6  9]
 [ 2  1  8 ...  3  6  2]
 [ 9  2  6 ...  6  1 10]]
[ 1  2  3  4  5  6  7  8  9 10]


/tmp/ipykernel_26491/4275189559.py:8: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  return([[int(b[a==i]) if i in a else 0 for i in np.unique(arr2d)] for a , b in num_counts_array])


[[1, 0, 2, 1, 1, 1, 0, 2, 2, 0],
 [2, 1, 3, 0, 1, 0, 1, 0, 1, 1],
 [0, 3, 0, 2, 3, 1, 0, 1, 0, 0],
 [1, 0, 2, 1, 0, 1, 0, 2, 1, 2],
 [2, 2, 2, 0, 0, 1, 1, 1, 1, 0],
 [1, 1, 1, 1, 1, 2, 0, 0, 2, 1]]

## 50. How to convert an array of arrays into a flat 1d arrray?

In [50]:
# Question: Convert array_of_arrays into a flat linear 1d array.

arr1 = np.arange(3)
arr2 = np.arange(3,7)
arr3 = np.arange(7,10)

arr_2d = np.concatenate([arr1, arr2, arr3])
print(arr_2d)

[0 1 2 3 4 5 6 7 8 9]
